[phases.setup]
nixPkgs = ['nodejs_22']

[phases.install]
cmds = [
  'corepack enable',
  'corepack prepare pnpm@latest --activate',
  'pnpm install --frozen-lockfile'
]

[phases.build]
cmds = [
  'pnpm prisma:generate',
  'pnpm build'
]

[start]
cmd = 'node dist/main.js'

